apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: tarasssito/hello-gitops
  newTag: c6485678ded9dbac5d8453f618293cf08d8d2548
